development:
  adapter: async
  url: ws://localhost:3000/cable
  allowed_request_origins:
    - http://localhost:3000

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: rubyist_production
